language: php

php:
  - 7.2
  - 7.3
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install

script:
  - composer ci

after_script:
  - |
    if [[ -f build/logs/clover.xml ]]; then
        wget https://scrutinizer-ci.com/ocular.phar
        php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
    fi
